from array_list import ArrayList

print("Демонстрація роботи ArrayList:")
lst = ArrayList()
print("Початкова довжина:", lst.length())
lst.append('a')
lst.append('b')
lst.append('c')
print("Після додавання a, b, c:", [lst.get(i) for i in range(lst.length())])
lst.insert('x', 1)
print("Після вставки 'x' на позицію 1:", [lst.get(i) for i in range(lst.length())])
deleted = lst.delete(2)
print(f"Видалено елемент на позиції 2: {deleted}")
print("Поточний список:", [lst.get(i) for i in range(lst.length())])
lst.append('a')
lst.append('b')
lst.append('a')
print("Після додавання a, b, a:", [lst.get(i) for i in range(lst.length())])
lst.deleteAll('a')
print("Після видалення всіх 'a':", [lst.get(i) for i in range(lst.length())])
print("Елемент на позиції 1:", lst.get(1))
clone = lst.clone()
print("Клонований список:", [clone.get(i) for i in range(clone.length())])
lst.reverse()
print("Реверсований список:", [lst.get(i) for i in range(lst.length())])
print("findFirst('b'):", lst.findFirst('b'))
print("findLast('b'):", lst.findLast('b'))
lst.clear()
print("Після очищення:", [lst.get(i) for i in range(lst.length())])
lst.append('m')
lst.append('n')
ext = ArrayList()
ext.append('x')
ext.append('y')
lst.extend(ext)
print("Після розширення списком ['x', 'y']:", [lst.get(i) for i in range(lst.length())]) 