from array_list import ArrayList
from linked_list import LinkedList

print("Демонстрація роботи ArrayList:")
lst = ArrayList()
print("Початкова довжина:", lst.length())
lst.append('a')
lst.append('b')
lst.append('c')
print("Після додавання a, b, c:", [lst.get(i) for i in range(lst.length())])
lst.insert('x', 1)
print("Після вставки 'x' на позицію 1:", [lst.get(i) for i in range(lst.length())])
deleted = lst.delete(2)
print(f"Видалено елемент на позиції 2: {deleted}")
print("Поточний список:", [lst.get(i) for i in range(lst.length())])
lst.append('a')
lst.append('b')
lst.append('a')
print("Після додавання a, b, a:", [lst.get(i) for i in range(lst.length())])
lst.deleteAll('a')
print("Після видалення всіх 'a':", [lst.get(i) for i in range(lst.length())])
if lst.length() > 1:
    print("Елемент на позиції 1:", lst.get(1))
clone = lst.clone()
print("Клонований список:", [clone.get(i) for i in range(clone.length())])
lst.reverse()
print("Реверсований список:", [lst.get(i) for i in range(lst.length())])
print("findFirst('b'):", lst.findFirst('b'))
print("findLast('b'):", lst.findLast('b'))
lst.clear()
print("Після очищення:", [lst.get(i) for i in range(lst.length())])
lst.append('m')
lst.append('n')
ext = ArrayList()
ext.append('x')
ext.append('y')
lst.extend(ext)
print("Після розширення списком ['x', 'y']:", [lst.get(i) for i in range(lst.length())])

print("\nДемонстрація роботи LinkedList:")
llst = LinkedList()
print("Початкова довжина:", llst.length())
llst.append('a')
llst.append('b')
llst.append('c')
print("Після додавання a, b, c:", [llst.get(i) for i in range(llst.length())])
llst.insert('x', 1)
print("Після вставки 'x' на позицію 1:", [llst.get(i) for i in range(llst.length())])
deleted = llst.delete(2)
print(f"Видалено елемент на позиції 2: {deleted}")
print("Поточний список:", [llst.get(i) for i in range(llst.length())])
llst.append('a')
llst.append('b')
llst.append('a')
print("Після додавання a, b, a:", [llst.get(i) for i in range(llst.length())])
llst.deleteAll('a')
print("Після видалення всіх 'a':", [llst.get(i) for i in range(llst.length())])
if llst.length() > 1:
    print("Елемент на позиції 1:", llst.get(1))
clone = llst.clone()
print("Клонований список:", [clone.get(i) for i in range(clone.length())])
llst.reverse()
print("Реверсований список:", [llst.get(i) for i in range(llst.length())])
print("findFirst('b'):", llst.findFirst('b'))
print("findLast('b'):", llst.findLast('b'))
llst.clear()
print("Після очищення:", [llst.get(i) for i in range(llst.length())])
llst.append('m')
llst.append('n')
ext2 = LinkedList()
ext2.append('x')
ext2.append('y')
llst.extend(ext2)
print("Після розширення списком ['x', 'y']:", [llst.get(i) for i in range(llst.length())]) 